### ISSUE TITLE
sim_design vignette

### ISSUE THREAD

**Issue by raffaem** [debruine/faux#104]
> For example, the following creates a 2w*2b design with 100 observations in each cell. The between-subject factor is pet with two levels (cat and dog). The within-subject factor is time with two levels (day and night).
> The data is sampled from a population where the mean for the cat_day cell is 10, the mean for the cat_night cell is 20, the mean for the dog_day cell is 15, and the mean for the dog_night cell is 25. All cells have a SD of 5 and all within-subject cells are correlated r = 0.5.

It looks to me that `time` has 4 factors (morning, noon, evening, night), and not 2, and so also the 4 means below doesn't make sense (should have 6 means, as specified in the code)

**Comment by debruine** [comment]
Thanks! I've updated the text to match the code (that I don't remember why I changed).
