### ISSUE TITLE
Feature request: negative binomial variables

### ISSUE THREAD

**Issue by hughjonesd** [debruine/faux#105]
These turn up in e.g. political science or any time you need count data but want to model the mean and variance separately.

I guess they could be supported by something as simple as

```r
norm2negbin <- function (x, size = NULL, prob = 0.5, mu = mean(x)) {
    p <- stats::pnorm(x, mu, sd)
    stats::qnbinom(p, size, prob, mu)
}
```

where only one of `prob` and `size` should be specified.

**Comment by debruine** [comment]
Added to new dev version (leaving issue open until I write the reverse nbinom2norm function)

**Comment by kayserb** [comment]
Thank you for this wonderful package! It's been critical for some power analyses I am doing. 

I just came to also request the negative binomial distribution, especially included with the `rmulti()`function. I would also like to request it be able to be specified by the mean and size (dispersion parameter) parameterization.

**Comment by debruine** [comment]
@kayserb - The rmulti() function will work with literally any distribution that has r***, p***, and q*** functions, so already works with nbinom, but I have also just added it to the dev version 1.2.1.9002 (to be submitted to VRAN soon)
