### ISSUE TITLE
Error interactive_design()

### ISSUE THREAD

**Issue by armelbrizuela** [debruine/faux#106]
Hello.

I am running interactive_design() (faux 1.2.1) in R 4.2.2. I found the following error and I do not know how to fix it.

`> interactive_design()`
How many within-subject factors do you have?: 
2
Name of within-subject factor 1: 
headline
How many levels of headline: 
2
Name of factor headline, level 1: 
TRUTH
Name of factor headline, level 2: 
FAKE
Name of within-subject factor 2: 
image
How many levels of image: 
2
Name of factor image, level 1: 
PIC
Name of factor image, level 2: 
NOPIC
How many between-subject factors do you have?: 
0
DV column name (default is y): 
accuracy
ID column name (default is id): 
id
Number of subjects: 
211
Means of TRUTH_PIC, TRUTH_NOPIC, FAKE_PIC, FAKE_NOPIC in condition accuracy: 
2.66, 2.52, 2.53, 2.41

**Error: The input is incorrect:**

**Comment by debruine** [comment]
Thanks for the bug report! I fixed the code in the dev version 1.2.1.9001 (just about to upload it to github) and the next CRAN version will not have this bug.
