### ISSUE TITLE
Issue with sim_design

### ISSUE THREAD

**Issue by Michaeladebolt** [debruine/faux#41]
Hello! I'm getting errors when trying to use the sim_design function. 

These are the errors:
Warning messages:
1: `fun.y` is deprecated. Use `fun` instead. 
2: `fun.ymin` is deprecated. Use `fun.min` instead. 
3: `fun.ymax` is deprecated. Use `fun.max` instead. 

I've attached a screenshot of the package versions that I'm currently using. 

Any idea what might be causing this?
Thanks!

![Screen Shot 2020-04-06 at 5 52 27 PM](https://user-images.githubusercontent.com/32584911/78618430-687c6400-782f-11ea-9466-88c125d5cf68.png)

**Comment by debruine** [comment]
It's due to the changes to ggplot. I just pushed an update, so re-install the package and it should work now. Thanks!

**Comment by Michaeladebolt** [comment]
Works perfectly now. Thank you for your quick response! 👍
