### ISSUE TITLE
Empirical = FALSE doesn't work

### ISSUE THREAD

**Issue by pmeiners** [debruine/faux#45]
Thank you for the very useful package. Unfortunately, I think the statement Empirical = FALSE in sim_design doesn't seem to do anything different than Empirical = TRUE.

Using faux_0.0.1.1

**Comment by debruine** [comment]
I added more unit tests to the package to check this and empirical seems to be working correctly for the examples I've tested. Can you give a specific example of the bug?

**Comment by pmeiners** [comment]
I'm sorry, it was an error on my end.
