### ISSUE TITLE
broom.mixed ggExtra dependency ?

### ISSUE THREAD

**Issue by jcolomb** [debruine/faux#75]
hi, I am not a package maker, please accept my apologies if the question is stupid.

I clone my fork of the package in Rstudio, install it via Rstudio button and push the check button, it failed asking for broom.mixed and ggExtra packages (that was the master branch, not the one with my changes). Once I installed the package, it runs smoothly and gives no error.

I thought the dependencies would be installed with `devtools::load_all(".")`, did I do something strange or are the dependencies of check different from the dependencies of the package, or ??

**Comment by debruine** [comment]
Hi Julien,

I’m so excited you’ve taken an interest in working on this! I’m busy marking dissertations, but I’ll have a look at your pull request next week and will definitely incorporate that into fun and add you to the contributors list :)

In the DESCRIPTION file, you’ll see that broom.mixed and ggextra are listed under Suggests, not Imports. I only use them in vignettes or examples, so they’re not required for the package functions to run and aren’t automatically imported. But Check runs the vignettes and examples, so will need them.

Cheers,
Lisa
