### ISSUE TITLE
Package example

### ISSUE THREAD

**Issue by statzhero** [debruine/faux#98]
I'm a bit confused by the example in `faux::rnorm_multi()`.

Shouldn't the correlations match the "r" argument? 

```
> b <- rnorm_multi(100, 3, c(0, .5, 1), 1, 
+                  r = c(0.2, -0.5, 0.5), 
+                  varnames=c("A", "B", "C"))
> cor(b)
           A         B          C
A  1.0000000 0.3193188 -0.4465425
B  0.3193188 1.0000000  0.4007359
C -0.4465425 0.4007359  1.0000000
```

**Comment by debruine** [comment]
The values of `m`, `sd` and `r` are the *population* parameters. Any sample will be close but unlikely to be identical. If you want them to be the *sample* parameters, set `empirical = TRUE`.
